Fix ImportError: cannot import name '_to_bytes' error
This constrains the requests-cache package to a version older than
0.6.0[1] in which the `_to_bytes` method was removed. This method is
used[2] in tvdb_api. Once use of the `_to_bytes` methods is removed
from tvdb_api, this version contraint can be removed.

Fixes #92

[1]: https://github.com/reclosedev/requests-cache/blob/master/HISTORY.md#060-2021-04-09
[2]: https://github.com/dbr/tvdb_api/blob/92e8c7cdf5bc1d923f9ed97dacbfd2b52bb4c893/tvdb_api.py